<div class="well"><h2>Einstellungen</h2></div>
<div class="well">
    <table class="table table-hover">
        <thead>
        <th>Client String</th>
        <th>Dav Client</th>
        </thead>
        <tbody>
            <?php foreach ($this->clients as $client) { ?>
                <tr id="client_<?php echo $client->getClid(); ?>">
                    <td><?php echo $client->getUseragent(); ?></td>
                    <td><input type="checkbox" class="clientCheckbox" <?php
            echo ' value="' . $client->getClid() . '" ';
            if ($client->getIsWebdavClient()) {
                echo 'checked="checked"';
            }
                ?>/></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <a href="" class="btn" id="davSaveButton">Speichern</a>
</div>
<script type="text/javascript">
    var davSaveUrl='<?php echo $this->url("cloud/default", array("controller"=>"settings", "action"=>"dav"));?>';
</script>
