<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FirePHP' => __DIR__ . '/src/SCToolbox/Log/FirePHP.class.php',
    'PasswordHash' => __DIR__ . '/src/SCToolbox/AAS/PasswordHash.php',
    'SCToolbox\Navagation\Navigation' => __DIR__ . '/src/SCToolbox/Navigation/Navigation.php',
    'SCToolbox\Navagation\Entity\Page' => __DIR__ . '/src/SCToolbox/Navigation/Entity/Page.php',
    'SCToolbox\Resources\Bundels\Plupload' => __DIR__ . '/src/SCToolbox/Resources/Bundels/Plupload.php',
    'SCToolbox\Upload\Plupload\View\Helper\PluploadHelper' => __DIR__ . '/src/SCToolbox/Upload/Plupload/View/Helper/PluploadHelper.php',
);
