<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FirePHP'       => __DIR__ . '/src/SCToolbox/Log/FirePHP.class.php',
    'PasswordHash'  => __DIR__ . '/src/SCToolbox/AAS/PasswordHash.php',
);