<?php echo $this->doctype() ?>


<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	</head>
<body>
Willkommen <?php echo $this->name?> <br />
<br />
Ich registrierung bei der Jungschar Birsfelden war erfolgreich<br />
und ein Benutzeraccount wurde f&uuml;r Sie angelegt.<br />
<br />
Ihr Benutzernamen lautet: <?php echo $this->username?><br />
<br />
Damit ihr Account funktionert m&uuml;ssen sie den Account noch aktivieren.<br />
Um den Account zu aktivieren klicken sie bitte <a href="<?php echo $this->url?>">hier</a><br />
<br /> 
Mit freundlichen Gr&uuml;ssen<br />
<br />
Ihr Jungschar Birsfelden Team<br />
</body>
</html>
