Willkommen <?php echo $this->name?>

Ich registrierung bei der Jungschar Birsfelden war erfolgreich
und ein Benutzeraccount wurde für Sie angelegt.

Ihr Benutzernamen lautet: <?php echo $this->username?>

Damit ihr Account funktionert müssen sie den Account noch aktivieren.
Um den Account zu aktivieren klicken sie bitte <?php echo $this->url?>
Mit freundlichen Grüssen

Ihr Jungschar Birsfelden Team
