<div id="fileReleadSection">
    <?php if (isset($this->currentFso)) { ?>
        <div class="well" id="pathSection">
            <?php echo $this->pathList()->show($this->currentFso->getPath2());?>
            <script lang="text/javascript" type="text/javascript">
                actualIdPath = "<?php echo $this->currentFso->getPath2()->getIdPath();?>";
            </script>
        </div>
    <?php } ?>
    <div class="well" id="fileSection"><table class="table">
            <thead>
                <tr>
                    <th>Dateinamen</th>
                    <th>Typ</th>
                    <th>Gr&ouml;sse</th>
                    <th>Erstelldatum</th>
                    <th>&Auml;nderungsdatum</th>
                    <th>Author</th>
                    <th>Zuletzt Bearbeitet von</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->fsos as $rootItem) {
                    $file = "fsFileLink";
                    if (!$rootItem->isFile())
                        $file = "fsFolderLink";
                    ?>
                    <tr id="fsorow_<?php echo $rootItem->getFsoid(); ?>">
                        <td>
                            <a id="fsoLink_<?php echo $rootItem->getFsoid() ?>" href="<?php
                if ($rootItem->isFile()) {
                    echo $this->url('cloud/downloadFile') . $rootItem->getPath(false);
                } else {
                    echo $this->url('cloud/showPaht') . $rootItem->getPath(false);
                }
                    ?>" class="<?php echo $file ?>"><?php echo $rootItem->getName(); ?></a>
                        </td>
                        <td><?php echo $rootItem->getTypeAsString(); ?></td>
                        <?php if ($rootItem->isFile()) { ?>
                            <td><?php echo $rootItem->getMetadata()->getSizeAsString(); ?></td>
                        <?php } else { ?><td>&nbsp;</td><?php } ?>
                        <td><?php echo $rootItem->getCreatedAsString(); ?></td>
                        <td><?php echo $rootItem->getLastModifiedAsString(); ?></td>
                        <td><?php echo $rootItem->getCreateUser(); ?></td>
                        <td><?php echo $rootItem->getEditUser(); ?></td>
                        <td>
                            <a href="javascript:showDialog(<?php echo $rootItem->getFsoid() ?>)">
                                <i class="icon-pencil"></i>
                            </a>
                            <a href="javascript:deleteObject('<?php echo $rootItem->getName(); ?>','<?php echo $rootItem->getType(); ?>', <?php echo $rootItem->getFsoid() ?>)"><i class="icon-trash"></i></a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>